### ISSUE TITLE
Reset the model won't work

### ISSUE THREAD

**Issue by ermalix** [bradleytrager/angular-combo-box#1]
When you try to reset the form/field it won't work, i.e $scope.mymodel.reset = ""

jsfiddle replicated

http://jsfiddle.net/bradleytrager/hdrnvmv2/2/

**Comment by bradleytrager** [comment]
This issue is fixed in v0.5.1, but in order to reset the element, `null` must be passed to the model.  An empty string is treated as an alternate value.  See [this](http://jsfiddle.net/bradleytrager/hdrnvmv2/3/) fiddle.
